//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace final.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IService1", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback isloginOperationCompleted;
        
        private System.Threading.SendOrPostCallback isaddOperationCompleted;
        
        private System.Threading.SendOrPostCallback resetOperationCompleted;
        
        private System.Threading.SendOrPostCallback changeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback showAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback isadOperationCompleted;
        
        private System.Threading.SendOrPostCallback islogOperationCompleted;
        
        private System.Threading.SendOrPostCallback cresetOperationCompleted;
        
        private System.Threading.SendOrPostCallback cchangeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback showAll2OperationCompleted;
        
        private System.Threading.SendOrPostCallback isafOperationCompleted;
        
        private System.Threading.SendOrPostCallback showName1OperationCompleted;
        
        private System.Threading.SendOrPostCallback showName2OperationCompleted;
        
        private System.Threading.SendOrPostCallback showName3OperationCompleted;
        
        private System.Threading.SendOrPostCallback showName4OperationCompleted;
        
        private System.Threading.SendOrPostCallback showName5OperationCompleted;
        
        private System.Threading.SendOrPostCallback adname1OperationCompleted;
        
        private System.Threading.SendOrPostCallback adname2OperationCompleted;
        
        private System.Threading.SendOrPostCallback adname3OperationCompleted;
        
        private System.Threading.SendOrPostCallback adname4OperationCompleted;
        
        private System.Threading.SendOrPostCallback adname5OperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteppOperationCompleted;
        
        private System.Threading.SendOrPostCallback delete1OperationCompleted;
        
        private System.Threading.SendOrPostCallback delete2OperationCompleted;
        
        private System.Threading.SendOrPostCallback delete3OperationCompleted;
        
        private System.Threading.SendOrPostCallback delete4OperationCompleted;
        
        private System.Threading.SendOrPostCallback delete5OperationCompleted;
        
        private System.Threading.SendOrPostCallback showAll3OperationCompleted;
        
        private System.Threading.SendOrPostCallback updateCapacityOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateItemOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::final.Properties.Settings.Default.final_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        public event isloginCompletedEventHandler isloginCompleted;
        
        /// <remarks/>
        public event isaddCompletedEventHandler isaddCompleted;
        
        /// <remarks/>
        public event resetCompletedEventHandler resetCompleted;
        
        /// <remarks/>
        public event changeeCompletedEventHandler changeeCompleted;
        
        /// <remarks/>
        public event showAllCompletedEventHandler showAllCompleted;
        
        /// <remarks/>
        public event isadCompletedEventHandler isadCompleted;
        
        /// <remarks/>
        public event islogCompletedEventHandler islogCompleted;
        
        /// <remarks/>
        public event cresetCompletedEventHandler cresetCompleted;
        
        /// <remarks/>
        public event cchangeeCompletedEventHandler cchangeeCompleted;
        
        /// <remarks/>
        public event showAll2CompletedEventHandler showAll2Completed;
        
        /// <remarks/>
        public event isafCompletedEventHandler isafCompleted;
        
        /// <remarks/>
        public event showName1CompletedEventHandler showName1Completed;
        
        /// <remarks/>
        public event showName2CompletedEventHandler showName2Completed;
        
        /// <remarks/>
        public event showName3CompletedEventHandler showName3Completed;
        
        /// <remarks/>
        public event showName4CompletedEventHandler showName4Completed;
        
        /// <remarks/>
        public event showName5CompletedEventHandler showName5Completed;
        
        /// <remarks/>
        public event adname1CompletedEventHandler adname1Completed;
        
        /// <remarks/>
        public event adname2CompletedEventHandler adname2Completed;
        
        /// <remarks/>
        public event adname3CompletedEventHandler adname3Completed;
        
        /// <remarks/>
        public event adname4CompletedEventHandler adname4Completed;
        
        /// <remarks/>
        public event adname5CompletedEventHandler adname5Completed;
        
        /// <remarks/>
        public event deleteppCompletedEventHandler deleteppCompleted;
        
        /// <remarks/>
        public event delete1CompletedEventHandler delete1Completed;
        
        /// <remarks/>
        public event delete2CompletedEventHandler delete2Completed;
        
        /// <remarks/>
        public event delete3CompletedEventHandler delete3Completed;
        
        /// <remarks/>
        public event delete4CompletedEventHandler delete4Completed;
        
        /// <remarks/>
        public event delete5CompletedEventHandler delete5Completed;
        
        /// <remarks/>
        public event showAll3CompletedEventHandler showAll3Completed;
        
        /// <remarks/>
        public event updateCapacityCompletedEventHandler updateCapacityCompleted;
        
        /// <remarks/>
        public event updateItemCompletedEventHandler updateItemCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/islogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void islogin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool isloginResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool isloginResultSpecified) {
            object[] results = this.Invoke("islogin", new object[] {
                        name,
                        password});
            isloginResult = ((bool)(results[0]));
            isloginResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void isloginAsync(string name, string password) {
            this.isloginAsync(name, password, null);
        }
        
        /// <remarks/>
        public void isloginAsync(string name, string password, object userState) {
            if ((this.isloginOperationCompleted == null)) {
                this.isloginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisloginOperationCompleted);
            }
            this.InvokeAsync("islogin", new object[] {
                        name,
                        password}, this.isloginOperationCompleted, userState);
        }
        
        private void OnisloginOperationCompleted(object arg) {
            if ((this.isloginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isloginCompleted(this, new isloginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isadd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isadd([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ip) {
            this.Invoke("isadd", new object[] {
                        name,
                        password,
                        email,
                        ip});
        }
        
        /// <remarks/>
        public void isaddAsync(string name, string password, string email, string ip) {
            this.isaddAsync(name, password, email, ip, null);
        }
        
        /// <remarks/>
        public void isaddAsync(string name, string password, string email, string ip, object userState) {
            if ((this.isaddOperationCompleted == null)) {
                this.isaddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisaddOperationCompleted);
            }
            this.InvokeAsync("isadd", new object[] {
                        name,
                        password,
                        email,
                        ip}, this.isaddOperationCompleted, userState);
        }
        
        private void OnisaddOperationCompleted(object arg) {
            if ((this.isaddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isaddCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/reset", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void reset([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string new_password, out bool resetResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool resetResultSpecified) {
            object[] results = this.Invoke("reset", new object[] {
                        name,
                        email,
                        new_password});
            resetResult = ((bool)(results[0]));
            resetResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void resetAsync(string name, string email, string new_password) {
            this.resetAsync(name, email, new_password, null);
        }
        
        /// <remarks/>
        public void resetAsync(string name, string email, string new_password, object userState) {
            if ((this.resetOperationCompleted == null)) {
                this.resetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnresetOperationCompleted);
            }
            this.InvokeAsync("reset", new object[] {
                        name,
                        email,
                        new_password}, this.resetOperationCompleted, userState);
        }
        
        private void OnresetOperationCompleted(object arg) {
            if ((this.resetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.resetCompleted(this, new resetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/changee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void changee([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string new_password, out bool changeeResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool changeeResultSpecified) {
            object[] results = this.Invoke("changee", new object[] {
                        name,
                        password,
                        new_password});
            changeeResult = ((bool)(results[0]));
            changeeResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void changeeAsync(string name, string password, string new_password) {
            this.changeeAsync(name, password, new_password, null);
        }
        
        /// <remarks/>
        public void changeeAsync(string name, string password, string new_password, object userState) {
            if ((this.changeeOperationCompleted == null)) {
                this.changeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnchangeeOperationCompleted);
            }
            this.InvokeAsync("changee", new object[] {
                        name,
                        password,
                        new_password}, this.changeeOperationCompleted, userState);
        }
        
        private void OnchangeeOperationCompleted(object arg) {
            if ((this.changeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.changeeCompleted(this, new changeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/showAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/finalwcf")]
        public Class1[] showAll() {
            object[] results = this.Invoke("showAll", new object[0]);
            return ((Class1[])(results[0]));
        }
        
        /// <remarks/>
        public void showAllAsync() {
            this.showAllAsync(null);
        }
        
        /// <remarks/>
        public void showAllAsync(object userState) {
            if ((this.showAllOperationCompleted == null)) {
                this.showAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowAllOperationCompleted);
            }
            this.InvokeAsync("showAll", new object[0], this.showAllOperationCompleted, userState);
        }
        
        private void OnshowAllOperationCompleted(object arg) {
            if ((this.showAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showAllCompleted(this, new showAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isad([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string ip) {
            this.Invoke("isad", new object[] {
                        name,
                        password,
                        email,
                        ip});
        }
        
        /// <remarks/>
        public void isadAsync(string name, string password, string email, string ip) {
            this.isadAsync(name, password, email, ip, null);
        }
        
        /// <remarks/>
        public void isadAsync(string name, string password, string email, string ip, object userState) {
            if ((this.isadOperationCompleted == null)) {
                this.isadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisadOperationCompleted);
            }
            this.InvokeAsync("isad", new object[] {
                        name,
                        password,
                        email,
                        ip}, this.isadOperationCompleted, userState);
        }
        
        private void OnisadOperationCompleted(object arg) {
            if ((this.isadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isadCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/islog", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void islog([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, out bool islogResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool islogResultSpecified) {
            object[] results = this.Invoke("islog", new object[] {
                        name,
                        password});
            islogResult = ((bool)(results[0]));
            islogResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void islogAsync(string name, string password) {
            this.islogAsync(name, password, null);
        }
        
        /// <remarks/>
        public void islogAsync(string name, string password, object userState) {
            if ((this.islogOperationCompleted == null)) {
                this.islogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnislogOperationCompleted);
            }
            this.InvokeAsync("islog", new object[] {
                        name,
                        password}, this.islogOperationCompleted, userState);
        }
        
        private void OnislogOperationCompleted(object arg) {
            if ((this.islogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.islogCompleted(this, new islogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/creset", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void creset([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string email, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string npassword, out bool cresetResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool cresetResultSpecified) {
            object[] results = this.Invoke("creset", new object[] {
                        name,
                        email,
                        npassword});
            cresetResult = ((bool)(results[0]));
            cresetResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void cresetAsync(string name, string email, string npassword) {
            this.cresetAsync(name, email, npassword, null);
        }
        
        /// <remarks/>
        public void cresetAsync(string name, string email, string npassword, object userState) {
            if ((this.cresetOperationCompleted == null)) {
                this.cresetOperationCompleted = new System.Threading.SendOrPostCallback(this.OncresetOperationCompleted);
            }
            this.InvokeAsync("creset", new object[] {
                        name,
                        email,
                        npassword}, this.cresetOperationCompleted, userState);
        }
        
        private void OncresetOperationCompleted(object arg) {
            if ((this.cresetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cresetCompleted(this, new cresetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/cchangee", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void cchangee([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string password, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string npassword, out bool cchangeeResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool cchangeeResultSpecified) {
            object[] results = this.Invoke("cchangee", new object[] {
                        name,
                        password,
                        npassword});
            cchangeeResult = ((bool)(results[0]));
            cchangeeResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void cchangeeAsync(string name, string password, string npassword) {
            this.cchangeeAsync(name, password, npassword, null);
        }
        
        /// <remarks/>
        public void cchangeeAsync(string name, string password, string npassword, object userState) {
            if ((this.cchangeeOperationCompleted == null)) {
                this.cchangeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncchangeeOperationCompleted);
            }
            this.InvokeAsync("cchangee", new object[] {
                        name,
                        password,
                        npassword}, this.cchangeeOperationCompleted, userState);
        }
        
        private void OncchangeeOperationCompleted(object arg) {
            if ((this.cchangeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cchangeeCompleted(this, new cchangeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/showAll2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/finalwcf")]
        public CustClass1[] showAll2() {
            object[] results = this.Invoke("showAll2", new object[0]);
            return ((CustClass1[])(results[0]));
        }
        
        /// <remarks/>
        public void showAll2Async() {
            this.showAll2Async(null);
        }
        
        /// <remarks/>
        public void showAll2Async(object userState) {
            if ((this.showAll2OperationCompleted == null)) {
                this.showAll2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowAll2OperationCompleted);
            }
            this.InvokeAsync("showAll2", new object[0], this.showAll2OperationCompleted, userState);
        }
        
        private void OnshowAll2OperationCompleted(object arg) {
            if ((this.showAll2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showAll2Completed(this, new showAll2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/isaf", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void isaf([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string service, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string route, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string routee, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string buses, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string capacity) {
            this.Invoke("isaf", new object[] {
                        service,
                        route,
                        routee,
                        buses,
                        capacity});
        }
        
        /// <remarks/>
        public void isafAsync(string service, string route, string routee, string buses, string capacity) {
            this.isafAsync(service, route, routee, buses, capacity, null);
        }
        
        /// <remarks/>
        public void isafAsync(string service, string route, string routee, string buses, string capacity, object userState) {
            if ((this.isafOperationCompleted == null)) {
                this.isafOperationCompleted = new System.Threading.SendOrPostCallback(this.OnisafOperationCompleted);
            }
            this.InvokeAsync("isaf", new object[] {
                        service,
                        route,
                        routee,
                        buses,
                        capacity}, this.isafOperationCompleted, userState);
        }
        
        private void OnisafOperationCompleted(object arg) {
            if ((this.isafCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.isafCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/showName1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] showName1() {
            object[] results = this.Invoke("showName1", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void showName1Async() {
            this.showName1Async(null);
        }
        
        /// <remarks/>
        public void showName1Async(object userState) {
            if ((this.showName1OperationCompleted == null)) {
                this.showName1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowName1OperationCompleted);
            }
            this.InvokeAsync("showName1", new object[0], this.showName1OperationCompleted, userState);
        }
        
        private void OnshowName1OperationCompleted(object arg) {
            if ((this.showName1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showName1Completed(this, new showName1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/showName2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] showName2() {
            object[] results = this.Invoke("showName2", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void showName2Async() {
            this.showName2Async(null);
        }
        
        /// <remarks/>
        public void showName2Async(object userState) {
            if ((this.showName2OperationCompleted == null)) {
                this.showName2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowName2OperationCompleted);
            }
            this.InvokeAsync("showName2", new object[0], this.showName2OperationCompleted, userState);
        }
        
        private void OnshowName2OperationCompleted(object arg) {
            if ((this.showName2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showName2Completed(this, new showName2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/showName3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] showName3() {
            object[] results = this.Invoke("showName3", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void showName3Async() {
            this.showName3Async(null);
        }
        
        /// <remarks/>
        public void showName3Async(object userState) {
            if ((this.showName3OperationCompleted == null)) {
                this.showName3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowName3OperationCompleted);
            }
            this.InvokeAsync("showName3", new object[0], this.showName3OperationCompleted, userState);
        }
        
        private void OnshowName3OperationCompleted(object arg) {
            if ((this.showName3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showName3Completed(this, new showName3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/showName4", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] showName4() {
            object[] results = this.Invoke("showName4", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void showName4Async() {
            this.showName4Async(null);
        }
        
        /// <remarks/>
        public void showName4Async(object userState) {
            if ((this.showName4OperationCompleted == null)) {
                this.showName4OperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowName4OperationCompleted);
            }
            this.InvokeAsync("showName4", new object[0], this.showName4OperationCompleted, userState);
        }
        
        private void OnshowName4OperationCompleted(object arg) {
            if ((this.showName4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showName4Completed(this, new showName4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/showName5", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] showName5() {
            object[] results = this.Invoke("showName5", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void showName5Async() {
            this.showName5Async(null);
        }
        
        /// <remarks/>
        public void showName5Async(object userState) {
            if ((this.showName5OperationCompleted == null)) {
                this.showName5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowName5OperationCompleted);
            }
            this.InvokeAsync("showName5", new object[0], this.showName5OperationCompleted, userState);
        }
        
        private void OnshowName5OperationCompleted(object arg) {
            if ((this.showName5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showName5Completed(this, new showName5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/adname1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void adname1([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            this.Invoke("adname1", new object[] {
                        name});
        }
        
        /// <remarks/>
        public void adname1Async(string name) {
            this.adname1Async(name, null);
        }
        
        /// <remarks/>
        public void adname1Async(string name, object userState) {
            if ((this.adname1OperationCompleted == null)) {
                this.adname1OperationCompleted = new System.Threading.SendOrPostCallback(this.Onadname1OperationCompleted);
            }
            this.InvokeAsync("adname1", new object[] {
                        name}, this.adname1OperationCompleted, userState);
        }
        
        private void Onadname1OperationCompleted(object arg) {
            if ((this.adname1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adname1Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/adname2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void adname2([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            this.Invoke("adname2", new object[] {
                        name});
        }
        
        /// <remarks/>
        public void adname2Async(string name) {
            this.adname2Async(name, null);
        }
        
        /// <remarks/>
        public void adname2Async(string name, object userState) {
            if ((this.adname2OperationCompleted == null)) {
                this.adname2OperationCompleted = new System.Threading.SendOrPostCallback(this.Onadname2OperationCompleted);
            }
            this.InvokeAsync("adname2", new object[] {
                        name}, this.adname2OperationCompleted, userState);
        }
        
        private void Onadname2OperationCompleted(object arg) {
            if ((this.adname2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adname2Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/adname3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void adname3([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            this.Invoke("adname3", new object[] {
                        name});
        }
        
        /// <remarks/>
        public void adname3Async(string name) {
            this.adname3Async(name, null);
        }
        
        /// <remarks/>
        public void adname3Async(string name, object userState) {
            if ((this.adname3OperationCompleted == null)) {
                this.adname3OperationCompleted = new System.Threading.SendOrPostCallback(this.Onadname3OperationCompleted);
            }
            this.InvokeAsync("adname3", new object[] {
                        name}, this.adname3OperationCompleted, userState);
        }
        
        private void Onadname3OperationCompleted(object arg) {
            if ((this.adname3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adname3Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/adname4", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void adname4([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            this.Invoke("adname4", new object[] {
                        name});
        }
        
        /// <remarks/>
        public void adname4Async(string name) {
            this.adname4Async(name, null);
        }
        
        /// <remarks/>
        public void adname4Async(string name, object userState) {
            if ((this.adname4OperationCompleted == null)) {
                this.adname4OperationCompleted = new System.Threading.SendOrPostCallback(this.Onadname4OperationCompleted);
            }
            this.InvokeAsync("adname4", new object[] {
                        name}, this.adname4OperationCompleted, userState);
        }
        
        private void Onadname4OperationCompleted(object arg) {
            if ((this.adname4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adname4Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/adname5", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void adname5([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name) {
            this.Invoke("adname5", new object[] {
                        name});
        }
        
        /// <remarks/>
        public void adname5Async(string name) {
            this.adname5Async(name, null);
        }
        
        /// <remarks/>
        public void adname5Async(string name, object userState) {
            if ((this.adname5OperationCompleted == null)) {
                this.adname5OperationCompleted = new System.Threading.SendOrPostCallback(this.Onadname5OperationCompleted);
            }
            this.InvokeAsync("adname5", new object[] {
                        name}, this.adname5OperationCompleted, userState);
        }
        
        private void Onadname5OperationCompleted(object arg) {
            if ((this.adname5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adname5Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/deletepp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deletepp(int index, [System.Xml.Serialization.XmlIgnoreAttribute()] bool indexSpecified) {
            this.Invoke("deletepp", new object[] {
                        index,
                        indexSpecified});
        }
        
        /// <remarks/>
        public void deleteppAsync(int index, bool indexSpecified) {
            this.deleteppAsync(index, indexSpecified, null);
        }
        
        /// <remarks/>
        public void deleteppAsync(int index, bool indexSpecified, object userState) {
            if ((this.deleteppOperationCompleted == null)) {
                this.deleteppOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteppOperationCompleted);
            }
            this.InvokeAsync("deletepp", new object[] {
                        index,
                        indexSpecified}, this.deleteppOperationCompleted, userState);
        }
        
        private void OndeleteppOperationCompleted(object arg) {
            if ((this.deleteppCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteppCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/delete1", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void delete1(int index, [System.Xml.Serialization.XmlIgnoreAttribute()] bool indexSpecified) {
            this.Invoke("delete1", new object[] {
                        index,
                        indexSpecified});
        }
        
        /// <remarks/>
        public void delete1Async(int index, bool indexSpecified) {
            this.delete1Async(index, indexSpecified, null);
        }
        
        /// <remarks/>
        public void delete1Async(int index, bool indexSpecified, object userState) {
            if ((this.delete1OperationCompleted == null)) {
                this.delete1OperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete1OperationCompleted);
            }
            this.InvokeAsync("delete1", new object[] {
                        index,
                        indexSpecified}, this.delete1OperationCompleted, userState);
        }
        
        private void Ondelete1OperationCompleted(object arg) {
            if ((this.delete1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete1Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/delete2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void delete2(int index, [System.Xml.Serialization.XmlIgnoreAttribute()] bool indexSpecified) {
            this.Invoke("delete2", new object[] {
                        index,
                        indexSpecified});
        }
        
        /// <remarks/>
        public void delete2Async(int index, bool indexSpecified) {
            this.delete2Async(index, indexSpecified, null);
        }
        
        /// <remarks/>
        public void delete2Async(int index, bool indexSpecified, object userState) {
            if ((this.delete2OperationCompleted == null)) {
                this.delete2OperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete2OperationCompleted);
            }
            this.InvokeAsync("delete2", new object[] {
                        index,
                        indexSpecified}, this.delete2OperationCompleted, userState);
        }
        
        private void Ondelete2OperationCompleted(object arg) {
            if ((this.delete2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete2Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/delete3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void delete3(int index, [System.Xml.Serialization.XmlIgnoreAttribute()] bool indexSpecified) {
            this.Invoke("delete3", new object[] {
                        index,
                        indexSpecified});
        }
        
        /// <remarks/>
        public void delete3Async(int index, bool indexSpecified) {
            this.delete3Async(index, indexSpecified, null);
        }
        
        /// <remarks/>
        public void delete3Async(int index, bool indexSpecified, object userState) {
            if ((this.delete3OperationCompleted == null)) {
                this.delete3OperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete3OperationCompleted);
            }
            this.InvokeAsync("delete3", new object[] {
                        index,
                        indexSpecified}, this.delete3OperationCompleted, userState);
        }
        
        private void Ondelete3OperationCompleted(object arg) {
            if ((this.delete3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete3Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/delete4", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void delete4(int index, [System.Xml.Serialization.XmlIgnoreAttribute()] bool indexSpecified) {
            this.Invoke("delete4", new object[] {
                        index,
                        indexSpecified});
        }
        
        /// <remarks/>
        public void delete4Async(int index, bool indexSpecified) {
            this.delete4Async(index, indexSpecified, null);
        }
        
        /// <remarks/>
        public void delete4Async(int index, bool indexSpecified, object userState) {
            if ((this.delete4OperationCompleted == null)) {
                this.delete4OperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete4OperationCompleted);
            }
            this.InvokeAsync("delete4", new object[] {
                        index,
                        indexSpecified}, this.delete4OperationCompleted, userState);
        }
        
        private void Ondelete4OperationCompleted(object arg) {
            if ((this.delete4Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete4Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/delete5", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void delete5(int index, [System.Xml.Serialization.XmlIgnoreAttribute()] bool indexSpecified) {
            this.Invoke("delete5", new object[] {
                        index,
                        indexSpecified});
        }
        
        /// <remarks/>
        public void delete5Async(int index, bool indexSpecified) {
            this.delete5Async(index, indexSpecified, null);
        }
        
        /// <remarks/>
        public void delete5Async(int index, bool indexSpecified, object userState) {
            if ((this.delete5OperationCompleted == null)) {
                this.delete5OperationCompleted = new System.Threading.SendOrPostCallback(this.Ondelete5OperationCompleted);
            }
            this.InvokeAsync("delete5", new object[] {
                        index,
                        indexSpecified}, this.delete5OperationCompleted, userState);
        }
        
        private void Ondelete5OperationCompleted(object arg) {
            if ((this.delete5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.delete5Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/showAll3", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/finalwcf")]
        public addy[] showAll3() {
            object[] results = this.Invoke("showAll3", new object[0]);
            return ((addy[])(results[0]));
        }
        
        /// <remarks/>
        public void showAll3Async() {
            this.showAll3Async(null);
        }
        
        /// <remarks/>
        public void showAll3Async(object userState) {
            if ((this.showAll3OperationCompleted == null)) {
                this.showAll3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnshowAll3OperationCompleted);
            }
            this.InvokeAsync("showAll3", new object[0], this.showAll3OperationCompleted, userState);
        }
        
        private void OnshowAll3OperationCompleted(object arg) {
            if ((this.showAll3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.showAll3Completed(this, new showAll3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/updateCapacity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateCapacity([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cap, int index, [System.Xml.Serialization.XmlIgnoreAttribute()] bool indexSpecified) {
            this.Invoke("updateCapacity", new object[] {
                        cap,
                        index,
                        indexSpecified});
        }
        
        /// <remarks/>
        public void updateCapacityAsync(string cap, int index, bool indexSpecified) {
            this.updateCapacityAsync(cap, index, indexSpecified, null);
        }
        
        /// <remarks/>
        public void updateCapacityAsync(string cap, int index, bool indexSpecified, object userState) {
            if ((this.updateCapacityOperationCompleted == null)) {
                this.updateCapacityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateCapacityOperationCompleted);
            }
            this.InvokeAsync("updateCapacity", new object[] {
                        cap,
                        index,
                        indexSpecified}, this.updateCapacityOperationCompleted, userState);
        }
        
        private void OnupdateCapacityOperationCompleted(object arg) {
            if ((this.updateCapacityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCapacityCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IService1/updateItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateItem(int ind, [System.Xml.Serialization.XmlIgnoreAttribute()] bool indSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string bus, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string cap) {
            this.Invoke("updateItem", new object[] {
                        ind,
                        indSpecified,
                        bus,
                        cap});
        }
        
        /// <remarks/>
        public void updateItemAsync(int ind, bool indSpecified, string bus, string cap) {
            this.updateItemAsync(ind, indSpecified, bus, cap, null);
        }
        
        /// <remarks/>
        public void updateItemAsync(int ind, bool indSpecified, string bus, string cap, object userState) {
            if ((this.updateItemOperationCompleted == null)) {
                this.updateItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateItemOperationCompleted);
            }
            this.InvokeAsync("updateItem", new object[] {
                        ind,
                        indSpecified,
                        bus,
                        cap}, this.updateItemOperationCompleted, userState);
        }
        
        private void OnupdateItemOperationCompleted(object arg) {
            if ((this.updateItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateItemCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/finalwcf")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/finalwcf")]
    public partial class addy {
        
        private string busField;
        
        private string capacityField;
        
        private string routeField;
        
        private string routeeField;
        
        private string serviceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Bus {
            get {
                return this.busField;
            }
            set {
                this.busField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Capacity {
            get {
                return this.capacityField;
            }
            set {
                this.capacityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Route {
            get {
                return this.routeField;
            }
            set {
                this.routeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Routee {
            get {
                return this.routeeField;
            }
            set {
                this.routeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Service {
            get {
                return this.serviceField;
            }
            set {
                this.serviceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/finalwcf")]
    public partial class CustClass1 {
        
        private string emailField;
        
        private string ipField;
        
        private string nameField;
        
        private string npasswordField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Npassword {
            get {
                return this.npasswordField;
            }
            set {
                this.npasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/finalwcf")]
    public partial class Class1 {
        
        private string emailField;
        
        private string ipField;
        
        private string nameField;
        
        private string new_passwordField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string New_password {
            get {
                return this.new_passwordField;
            }
            set {
                this.new_passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void isloginCompletedEventHandler(object sender, isloginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class isloginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal isloginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool isloginResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool isloginResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void isaddCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void resetCompletedEventHandler(object sender, resetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class resetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal resetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool resetResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool resetResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void changeeCompletedEventHandler(object sender, changeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal changeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool changeeResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool changeeResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void showAllCompletedEventHandler(object sender, showAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Class1[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Class1[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void isadCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void islogCompletedEventHandler(object sender, islogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class islogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal islogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool islogResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool islogResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void cresetCompletedEventHandler(object sender, cresetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cresetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cresetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool cresetResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool cresetResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void cchangeeCompletedEventHandler(object sender, cchangeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cchangeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cchangeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool cchangeeResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool cchangeeResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void showAll2CompletedEventHandler(object sender, showAll2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showAll2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showAll2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CustClass1[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CustClass1[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void isafCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void showName1CompletedEventHandler(object sender, showName1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showName1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showName1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void showName2CompletedEventHandler(object sender, showName2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showName2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showName2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void showName3CompletedEventHandler(object sender, showName3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showName3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showName3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void showName4CompletedEventHandler(object sender, showName4CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showName4CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showName4CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void showName5CompletedEventHandler(object sender, showName5CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showName5CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showName5CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void adname1CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void adname2CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void adname3CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void adname4CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void adname5CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void deleteppCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void delete1CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void delete2CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void delete3CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void delete4CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void delete5CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void showAll3CompletedEventHandler(object sender, showAll3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class showAll3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal showAll3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public addy[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((addy[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void updateCapacityCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void updateItemCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591